### ISSUE TITLE
Swipe right to play the song next

### ISSUE THREAD

**Issue by siggi1984** [Maloy-Android/Muzza#1]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Swipe right to play the song next

### Why do you want this feature?

It would make adding titles to the queue a lot easier.

**Comment by Maloy-Android** [comment]
Good idea

**Comment by siggi1984** [comment]
this function is now available in the OuterTune fork

**Comment by immortaljam** [comment]
nah I think swipe right to add to queue would be better (similar to spotify)

**Comment by siggi1984** [comment]
> nah I think swipe right to add to queue would be better (similar to spotify)

Play next ist better

**Comment by immortaljam** [comment]
> > nah I think swipe right to add to queue would be better (similar to spotify)
> 
> Play next ist better

nah queue is better

**Comment by siggi1984** [comment]
what a kindergarten
