### ISSUE TITLE
crashes when trying to restore backup

### ISSUE THREAD

**Issue by immortaljam** [Maloy-Android/Muzza#10]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Maloy-Android/Muzza/actions/workflows/build.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

I go to restore
click on innertune backup file
it crashes and app closes

### Expected behavior

it shouldn't crash

### Actual behavior

it crashes
im not able to reopen app either, it keeps closing, I have to clear data to be able to use app again

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/b6c4646c-d01f-4a25-8fd5-c47eb4839edc

https://github.com/user-attachments/assets/978b6dab-6634-4871-b9ff-b14b1c9104b9

### Logs

.

### Muzza version

0.6.3 final 

### Android version

android 12

### Additional information

ty for ur help

**Comment by Maloy-Android** [comment]
This is because when adding new changes to work with Youtube-Music syncs, changes are made that result in losing the ability to stop the backup backup, this will continue until I finish working on the sync

**Comment by Maloy-Android** [comment]
![Screenshot_2024-11-26-13-33-26-265_com android chrome](https://github.com/user-attachments/assets/0726c259-3d10-4393-9cc2-188d639bcc00)

**Comment by Maloy-Android** [comment]
See Warning

**Comment by immortaljam** [comment]
> ![Screenshot_2024-11-26-13-33-26-265_com android chrome](https://private-user-images.githubusercontent.com/177887593/389908072-0726c259-3d10-4393-9cc2-188d639bcc00.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MjE2NzcsIm5iZiI6MTczMjYyMTM3NywicGF0aCI6Ii8xNzc4ODc1OTMvMzg5OTA4MDcyLTA3MjZjMjU5LTNkMTAtNDM5My05Y2MyLTE4OGQ2MzliY2MwMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQxMTQyNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMWFhYTdkMjJlYzliZjJhYjJmZDJiNjYxZWUzNDNhMzI2OTU2OWEyZDMxYjlmOTExZTI1MTIzZDA3ZTdjNGQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.N-oXxI94TCh-X4o8bbKksFyjw_4EXhV8Zp8qqIcVEtc)

alright, thank you for the response. is there any version where I can restore backup?

**Comment by Maloy-Android** [comment]
No
