### ISSUE TITLE
Download over songs already downloaded

### ISSUE THREAD

**Issue by Roxo7777** [Maloy-Android/Muzza#7]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

When in some playlist or album there are already some songs already downloaded and others not, when I click to download the playlist/album, it redownloads the songs that were already downloaded. 

The feature could serve as when we try to put a song already placed in a playlist, simply skip the item that is already downloaded, not demoting it, just downloading the items that are not downloadedThe feature could serve as when we try to put a song already placed in a playlist, simply skip the item that is already downloaded, not downgrading it, just downloading the items that are not downloaded, is simple. 

### Why do you want this feature?

When you downgrade everything again, it takes longer when it's a large playlist.

**Comment by Maloy-Android** [comment]
![Screenshot_2024-11-20-16-45-14-215_com maloy muzza](https://github.com/user-attachments/assets/77037fde-b24f-4147-b0cc-c1c5a3d876dc)

**Comment by Maloy-Android** [comment]
Redownloading only downloads tracks that are not downloaded

**Comment by Roxo7777** [comment]
> Redownloading only downloads tracks that are not downloaded

On mine, download the songs again, I'll send a screen recording.
